name: build sing-box with proxy providers

on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Debug build
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: PuerNya/sing-box
          ref: outbound-providers
      - name: with_clash_ui
        id: dashboard
        run: |  
          git submodule init
          git submodule update
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
      - name: Add cache to Go proxy
        run: |
          version=`git rev-parse HEAD`
          mkdir build
          pushd build
          go mod init build
          go get -v github.com/sagernet/sing-box@$version
          popd
        continue-on-error: true
      - name: Run Test
        run: |
          go test -v ./...
  cross:
    strategy:
      matrix:
        include:
          # linux
          - name: linux-arm64
            goos: linux
            goarch: arm64
          - name: linux-armv7
            goos: linux
            goarch: arm
            goarm: 7

          # android
          - name: android-arm64
            goos: android
            goarch: arm64
            goarm: 7

      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      GOARM: ${{ matrix.goarm }}
      GOMIPS: ${{ matrix.gomips }}
      CGO_ENABLED: 0
      TAGS: with_gvisor,with_quic,with_wireguard,with_clash_api,with_acme,with_providers,with_clash_ui,with_utls
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: PuerNya/sing-box
          ref: outbound-providers
      - name: with_clash_ui
        id: dashboard
        run: |  
          git submodule init
          git submodule update
      - name: Get latest go version
        id: version
        run: |
          ls -lh
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
      - name: Build
        id: build
        run: make
      - name: Test
        run: |
          echo ${{ contains(matrix.name, 'windows') }}
          echo ${{ matrix.name }}
      - name: Rename Windows
        if: ${{ contains(matrix.name, 'windows') }}
        run: mv sing-box* sing-box-${{ matrix.name }}.exe
      - name: Rename
        if: ${{ contains(matrix.name, 'linux') || contains(matrix.name, 'bsd') || contains(matrix.name, 'darwin') || contains(matrix.name, 'android') }}
        run: mv sing-box* sing-box-${{ matrix.name }}
      #- name: Upload artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: sing-box-${{ matrix.name }}
      #    path: sing-box*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          files: |
            sing-box*
